// ==UserScript==
// @name         ZyBooks Dark
// @namespace    http://tampermonkey.net/
// @version      1.0.0
// @description  Lazy attempt at dark mode on Zybooks :D
// @author       BestBuy
// @match        https://*.zybooks.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=zybooks.com
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';
    GM_addStyle(`
body,
.route-container {
    background-color: #262c36;
}

h1,
h2,
h3,
h4,
h5,
h6,
.body-text,
.validator-text,
.strict-equal-assert-result .type-message,
.application-notification,
.application-notification .c-notification__content,
.ace-editor-container .drop-file-message,
.ai-zylab-helper .ai-conversation-container .ai-message-container .ai-message,
.zb-button,
.zb-feedback .expanded-feedback .zb-control-row .more-info,
.content-resource.container-content-resource .container-resource-payload details>summary,
.content-resource.container-content-resource.table .table-insert-editor .fr-toolbar .fr-btn:last-child,
.pythonTutor .ExecutionVisualizer #vcrControls .button,
.availability-options .copy-pw-clipboard,
.view-request-card .back-to-library-link,
.review-adoption .back-to-library-link,
.not-found-page .copy-pw-clipboard,
.zybook-chapter-print-page .copy-pw-clipboard,
.zybook-chapter-section-page .copy-pw-clipboard,
.zybook-chapter-section-loading-page .copy-pw-clipboard,
.zybook-create-section-page .copy-pw-clipboard,
.zybook-edit-section-page .copy-pw-clipboard,
.zybook-error-page .copy-pw-clipboard,
.zylab-ui-page .copy-pw-clipboard,
.zybook-unused-section-loading-page .copy-pw-clipboard,
.zybook-unused-section-page .copy-pw-clipboard,
.section-preview-modal .copy-pw-clipboard,
.not-found-page .section-header-row .section-action-container .edit-lab-link,
.zybook-chapter-print-page .section-header-row .section-action-container .edit-lab-link,
.zybook-chapter-section-page .section-header-row .section-action-container .edit-lab-link,
.zybook-chapter-section-loading-page .section-header-row .section-action-container .edit-lab-link,
.zybook-create-section-page .section-header-row .section-action-container .edit-lab-link,
.zybook-edit-section-page .section-header-row .section-action-container .edit-lab-link,
.zybook-error-page .section-header-row .section-action-container .edit-lab-link,
.zylab-ui-page .section-header-row .section-action-container .edit-lab-link,
.zybook-unused-section-loading-page .section-header-row .section-action-container .edit-lab-link,
.zybook-unused-section-page .section-header-row .section-action-container .edit-lab-link,
.section-preview-modal .section-header-row .section-action-container .edit-lab-link,
.zybook-zylab-similarity-page .zb-toolbar .exit-button,
.zybook-advanced-zylab-similarity-page .zb-toolbar .exit-button,
.assignment-section-summary .next-section-link,
.instructor-note-container .show-edit-instructor-note-icon,
.modify-section .toolbar-container .toolbar-card .show-me-how-link,
.subscribe-student-panel .already-paid,
.zybook-configure-panel .panel-content .move-sections-button,
.student-instructions-modal .copy-instructions-to-clipboard-button,
.multiple-choice-exam-question,
.zb-nav-menu .chapter-labels .nav-item-label,
.zb-nav-menu .chapter-labels .nav-item-label-empty,
.zb-nav-menu .chapter-labels .nav-item-label-exam,
.zb-nav-menu .chapter-labels .nav-item-label-hidden,
.zb-nav-menu .chapter-labels .nav-item-label-lab,
.zb-nav-menu .chapter-labels .nav-item-label-optional,
.zb-nav-menu .section-labels .nav-item-label,
.zb-nav-menu .section-labels .nav-item-label-empty,
.zb-nav-menu .section-labels .nav-item-label-exam,
.zb-nav-menu .section-labels .nav-item-label-hidden,
.zb-nav-menu .section-labels .nav-item-label-lab,
.zb-nav-menu .section-labels .nav-item-label-optional,
.zb-progress-circular,
.zb-footer,
.bread-crumbs,
.exercise-info-modal h2,
.interactive-activity-container .activity-payload,
.MLK__rows>.row .action.check,
.class-statistics .lab-statistics-row .stat-container,
.instructor-view-student-submissions p,
.instructor-view-student-submissions .manual-test,
.lab-statistics-charts .chart-container,
.zylabs-view-test-bench,
.zylabs-view-test-bench .test .test-description,
.test-results-modal .testing-instructions-list,
.zystudio-student-activity .zystudio-manual-test,
.zylabs-edit .code,
.zylabs-edit .run-message,
.zylabs-edit .test-results-modal .testing-instructions-list,
.zylabs-edit .save-lab-modal p,
.zylabs-edit .save-lab-modal td,
.zylabs-edit .lab-spec .section-card,
.zylabs-edit .lab-spec .matlab-points,
.file-io .instructions,
.file-io .error-message,
.develop-mode .instructions,
.zylabs-edit .test-bench .test-summary,
.zylabs-edit .student-files .file-editor .editor-container .ace-editor-header .description,
.mathworks-editor-card .message,
.zybook-unit-test-help-page .zybook-section-title,
.catalog-page h1,
.catalog-page .class-instructions .instructions,
.privacy-page,
.tos-page,
.view-request-card,
.review-adoption,
.zybook-chapter-add-lab-page .add-lab-card,
.zybook-chapter-add-lab-page h3,
.zybook-chapter-add-lab-page .description,
.zybook-chapter-add-lab-page .selected-labs-text,
.zybook-chapter-add-lab-page .zb-table table .name-column .lab-title,
.zybook-getting-started-page .explanatory-text,
.zybook-getting-started-page .video-list,
.zybook-content-explorer-page .zybook-outline .term-definition,
.zybook-content-explorer-printable-page .zybook-outline .term-definition,
.zybook-content-explorer-page .zybook-outline .resource-info-container .resource-caption,
.zybook-content-explorer-printable-page .zybook-outline .resource-info-container .resource-caption,
.zybook-chapter-section-page .assignment-section-announcement .section-announcement-block-content,
.zybook-chapter-section-page .assignment-completion-summary-card,
.not-found-page .zybook-section,
.zybook-chapter-print-page .zybook-section,
.zybook-chapter-section-page .zybook-section,
.zybook-chapter-section-loading-page .zybook-section,
.zybook-create-section-page .zybook-section,
.zybook-edit-section-page .zybook-section,
.zybook-error-page .zybook-section,
.zylab-ui-page .zybook-section,
.zybook-unused-section-loading-page .zybook-section,
.zybook-unused-section-page .zybook-section,
.section-preview-modal .zybook-section,
.not-found-page .zybook-section .zybook-section-title,
.zybook-chapter-print-page .zybook-section .zybook-section-title,
.zybook-chapter-section-page .zybook-section .zybook-section-title,
.zybook-chapter-section-loading-page .zybook-section .zybook-section-title,
.zybook-create-section-page .zybook-section .zybook-section-title,
.zybook-edit-section-page .zybook-section .zybook-section-title,
.zybook-error-page .zybook-section .zybook-section-title,
.zylab-ui-page .zybook-section .zybook-section-title,
.zybook-unused-section-loading-page .zybook-section .zybook-section-title,
.zybook-unused-section-page .zybook-section .zybook-section-title,
.section-preview-modal .zybook-section .zybook-section-title,
.not-found-page .section-banner,
.zybook-chapter-print-page .section-banner,
.zybook-chapter-section-page .section-banner,
.zybook-chapter-section-loading-page .section-banner,
.zybook-create-section-page .section-banner,
.zybook-edit-section-page .section-banner,
.zybook-error-page .section-banner,
.zylab-ui-page .section-banner,
.zybook-unused-section-loading-page .section-banner,
.zybook-unused-section-page .section-banner,
.section-preview-modal .section-banner,
.not-found-page .instructor-hidden-message,
.zybook-chapter-print-page .instructor-hidden-message,
.zybook-chapter-section-page .instructor-hidden-message,
.zybook-chapter-section-loading-page .instructor-hidden-message,
.zybook-create-section-page .instructor-hidden-message,
.zybook-edit-section-page .instructor-hidden-message,
.zybook-error-page .instructor-hidden-message,
.zylab-ui-page .instructor-hidden-message,
.zybook-unused-section-loading-page .instructor-hidden-message,
.zybook-unused-section-page .instructor-hidden-message,
.section-preview-modal .instructor-hidden-message,
.zybook-zylab-similarity-page,
.zybook-advanced-zylab-similarity-page,
.assignment-details,
.assignment-due-date-lms-details,
.assignment-summary,
.zybook-section .instructor-note,
.zybook-outline-filter,
.zylab-table-section-header .info-text,
.zylab-table-section-header .zybook-graphic-container .zybook-details,
.table-of-contents .section-selection-header .header-title,
.table-of-contents .activity-selection-header .header-title,
.table-of-contents .configure-header .header-title,
.table-of-contents .section-assignment-header .header-title,
.table-of-contents .detail-text,
.chapter-item .section-list-container .empty-chapter-text,
.section-assignment-details .assignment-choices-container .no-activities-text,
.lti-instructions-panel .no-assignments-text,
.lti-instructions-panel .assignment-info-text,
.lti-instructions-panel .hidden-assignments-text,
.my-class-instructor-panel .panel-content .scrollable-content .manage-class-ul,
.zybook-configure-panel .panel-content .instructions-text,
.zybook-configure-panel .error-message,
.about-page-modal,
.about-page-modal .new-sections-table,
.catalog-item-info-modal,
.catalog-item-info-modal h2,
.catalog-take-class-modal h1,
.catalog-extension-modal,
.manage-class-modal .warning-message,
.manage-class-modal .confirmation-message,
.manage-class-modal .updated-message,
.python-course-modal,
.request-refund-modal h1,
.accessibility-modal h1,
.student-instructions-modal h1,
.student-instructions-modal .instructions-text,
.mathworks-tos-modal,
.view-receipt-modal,
.add-zylab-options,
.add-zylab-options h1,
.clone-zylab,
.clone-zylab h1,
.zybook-ordering-preview .info-list,
.webinar-info-modal h1,
.zybook-extension-modal,
.zybook-analytics-dashboard .highcharts-title,
.zybook-analytics-dashboard .highcharts-axis-title,
.zybook-analytics-dashboard .tooltip-container,
.activity-filter,
.table-of-contents h3,
.chapter-item .chapter-item-controls .chapter-title,
.bread-crumbs a,
.zb-modal .zb-modal-content h1,
.student-submit-assignment-modal .zb-modal-content,
.student-submit-assignment-modal .zb-modal-content h1,
.zybook-panel .tabs .full-tab>p,
.zybook-panel .tabs .full-tab .label,
.zb-author-menu .ember-basic-dropdown-trigger,
.zb-menu .ember-basic-dropdown-trigger,
.zybook-panel .base-panel .text-blue-grey-500,
.assignments-panel .text-blue-grey-500,
.my-class-student-panel h3,
.section-header,
.lab-statistics-charts .chart-container .chart-label,
.zybook-zylab-similarity-page .matches-container .matches-list-container h3,
.zybook-advanced-zylab-similarity-page .matches-container .matches-list-container h3,
.about-page-modal h3,
.zb-input-container label .zb-input-container:focus>label,
.zb-input-container.value-present>label,
.zb-select-container .select select,
.zb-input-label,
.power-select-label,
.zylabs-edit .lab-spec .lab-instructions-label,
.basic-options .additionalflags-label,
.basic-options .command-label,
.develop-mode .load-data-label,
.result-set-test .load-data-label,
.zybook-chapter-add-lab-page .select-label,
.zybook-chapter-add-lab-page .zb-table table .section-column-header th,
.zybook-outline-filter .options .option .parts-count,
.zb-checkbox.label-present label .zb-input-container input,
.section-header,
.lab-statistics-charts .chart-container .chart-label,
.zybook-zylab-similarity-page .matches-container .matches-list-container h3,
.zybook-advanced-zylab-similarity-page .matches-container .matches-list-container h3,
.about-page-modal h3 {
    color: #ffffff;
}

.not-found-page .section-nav,
.zybook-chapter-print-page .section-nav,
.zybook-chapter-section-page .section-nav,
.zybook-chapter-section-loading-page .section-nav,
.zybook-create-section-page .section-nav,
.zybook-edit-section-page .section-nav,
.zybook-error-page .section-nav,
.zylab-ui-page .section-nav,
.zybook-unused-section-loading-page .section-nav,
.zybook-unused-section-page .section-nav,
.section-preview-modal .section-nav,
.table-of-contents .toc-header-common,
.table-of-contents .toc-header,
.zybook-panel,
.zybook-panel .tabs .full-tab,
.zybook-panel .tabs .full-tab.active,
.zybook-panel .tabs .full-tab.inactive,
.section-settings-menu,
.unknown-content-resource,
.not-found-page .time-remaining-toast,
.zybook-chapter-print-page .time-remaining-toast,
.zybook-chapter-section-page .time-remaining-toast,
.zybook-chapter-section-loading-page .time-remaining-toast,
.zybook-create-section-page .time-remaining-toast,
.zybook-edit-section-page .time-remaining-toast,
.zybook-error-page .time-remaining-toast,
.zylab-ui-page .time-remaining-toast,
.zybook-unused-section-loading-page .time-remaining-toast,
.zybook-unused-section-page .time-remaining-toast,
.section-preview-modal .time-remaining-toast,
.insert-content.in-side-menu,
.insert-content.in-section.expanded.inverted,
.modify-section .toolbar-container .toolbar-card,
.modify-section .zybook-exam-section .access-controls,
.modify-section .zybook-exam-section .result-details,
.zb-card,
.interactive-activity-container .activity-title-bar,
.resource-container,
.interactive-activity-container,
.static-container,
.not-found-page .section-nav,
.zybook-chapter-print-page .section-nav,
.zybook-chapter-section-page .section-nav,
.zybook-chapter-section-loading-page .section-nav,
.zybook-create-section-page .section-nav,
.zybook-edit-section-page .section-nav,
.zybook-error-page .section-nav,
.zylab-ui-page .section-nav,
.zybook-unused-section-loading-page .section-nav,
.zybook-unused-section-page .section-nav,
.section-preview-modal .section-nav,
.interactive-activity-container .activity-description,
.interactive-activity-container .activity-type,
.toolbar,
.top-toolbar,
.zb-modal .zb-modal-content {
    background-color: #1a1a1a;
}

.content-tools-app .term,
.zybook-section .term,
.test-question .term,
.unique .term,
.material-icons.blue-grey,
.material-icons-outlined.blue-grey,
.material-icons-two-tone.blue-grey,
.material-icons-round.blue-grey,
.material-icons-sharp.blue-grey,
.static-container .static-container-title,
.zb-simple-expandable .toggle-button .title,
.content-tools-app .common-error,
.content-tools-app .good-practice,
.zybook-section .common-error,
.zybook-section .good-practice,
.test-question .common-error,
.test-question .good-practice,
.unique .common-error,
.unique .good-practice {
    color: #fc6c04;
}

.content-tools-app .table table th,
.zybook-section .table table th,
.test-question .table table th,
.unique .table table th,
.content-tools-app .table .dbTable th,
.zybook-section .table .dbTable th,
.test-question .table .dbTable th,
.unique .table .dbTable th,
.content-tools-app .zytable th,
.zybook-section .zytable th,
.test-question .zytable th,
.unique .zytable th,
.content-tools-app table.dbTable th,
.content-tools-app .dbtable th,
.zybook-section table.dbTable th,
.zybook-section .dbtable th,
.test-question table.dbTable th,
.test-question .dbtable th,
.unique table.dbTable th,
.unique .dbtable th,
.test-result .sql-output-container .result-table-container table th,
.multiple-choice-exam-question .zytable th,
.zb-rich-text-editor .zytable th,
.content-resource.container-content-resource.table table th,
.vm-it-lab-content-resource .vm-it-lab-markdown table th,
.markdown-content-resource table th,
.lab-spec table th,
.block-ordering-pa-2-column table th,
.two-reorderable-lists table th,
.develop-container .sql-output.result-set-container .result-table-container table th {
    background-color: #f57c00;
    border: 1px solid #f5f5f5;
}

.table-column-style,
.content-tools-app .table table td,
.zybook-section .table table td,
.test-question .table table td,
.unique .table table td,
.content-tools-app .table .dbTable td,
.zybook-section .table .dbTable td,
.test-question .table .dbTable td,
.unique .table .dbTable td,
.content-tools-app .zytable td,
.zybook-section .zytable td,
.test-question .zytable td,
.unique .zytable td,
.content-tools-app table.dbTable td,
.content-tools-app .dbtable td,
.zybook-section table.dbTable td,
.zybook-section .dbtable td,
.test-question table.dbTable td,
.test-question .dbtable td,
.unique table.dbTable td,
.unique .dbtable td,
.test-result .sql-output-container .result-table-container table td,
.multiple-choice-exam-question .zytable td,
.zb-rich-text-editor .zytable td,
.content-resource.container-content-resource.table table td,
.vm-it-lab-content-resource .vm-it-lab-markdown table td,
.markdown-content-resource table td,
.lab-spec table td,
.block-ordering-pa-2-column table td,
.two-reorderable-lists table td,
.develop-container .sql-output.result-set-container .result-table-container table td {
    background-color: #2b2b2b;
}

.content-tools-app div.code,
.content-tools-app .code,
.content-tools-app .zyblock,
.zybook-section div.code,
.zybook-section .code,
.zybook-section .zyblock,
.test-question div.code,
.test-question .code,
.test-question .zyblock,
.unique div.code,
.unique .code,
.unique .zyblock {
    background-color: #000000;
}

.animation-canvas {
    background-color: #2b2b2b;
    border-radius: 8px;
}

code,
pre {
    color: aqua;
}

.animation-caption,
.zb-checkbox.label-present label,
.highlight .n {
    color: #f57c00;
}

.highlight .c1 {
    color: #f9b424;
}

.highlight .o {
    color: #4ac74b;
}

.highlight .mi,
.highlight .mf {
    color: #0fcadf;
}

.highlight .p {
    color: #a335f3;
}
    `);
})();

